# Generated by Django 5.1.7 on 2025-03-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('nro_factura', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cuit', models.CharField(max_length=11)),
                ('apellido', models.CharField(max_length=200)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
