# Generated by Django 5.1.7 on 2025-03-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_factura', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('razon_social', models.CharField(max_length=100)),
                ('cuit', models.CharField(max_length=11)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
