# Generated by Django 5.1.7 on 2025-03-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='id',
        ),
        migrations.AlterField(
            model_name='compra',
            name='nro_factura',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
